//! Natural-edge reductions via graph subtype relaxation.
//!
//! These reductions are trivial: a problem on a specific graph type
//! (e.g., `Triangular`) can always be solved as the same problem on a
//! more general graph type (e.g., `SimpleGraph`), since the specific
//! graph *is* a general graph. The solution mapping is identity.
//!
//! Each reduction is generated by [`impl_natural_reduction!`].

use crate::impl_natural_reduction;
use crate::models::graph::MaximumIndependentSet;
use crate::reduction;
use crate::topology::{SimpleGraph, Triangular};

impl_natural_reduction!(MaximumIndependentSet, Triangular, SimpleGraph, i32);

#[cfg(all(test, feature = "ilp"))]
#[path = "../unit_tests/rules/natural.rs"]
mod tests;
