# Codecov configuration for problem-reductions
# https://docs.codecov.com/docs/codecov-yaml

coverage:
  precision: 2
  round: down
  range: "90...100"

  status:
    project:
      default:
        target: 95%
        threshold: 2%
    patch:
      default:
        target: 95%
        threshold: 2%

# Exclude proc-macro crate from coverage since it runs at compile time
# and traditional runtime coverage tools cannot measure it.
# Exclude CLI crate from patch coverage: it is a thin dispatch layer
# with many boilerplate type-dispatch match arms that are tested
# end-to-end via integration tests, not amenable to 95% line coverage.
ignore:
  - "problemreductions-macros/**/*"
  - "problemreductions-cli/**/*"
