# Codecov configuration for problem-reductions
# https://docs.codecov.com/docs/codecov-yaml

coverage:
  precision: 2
  round: down
  range: "90...100"

  status:
    project:
      default:
        target: 95%
        threshold: 2%
    patch:
      default:
        target: 95%
        threshold: 2%

# Exclude proc-macro crate from coverage since it runs at compile time
# and traditional runtime coverage tools cannot measure it
ignore:
  - "problemreductions-macros/**/*"
