// Julia ProblemReductions.jl parity tests.
//
// Most tests have been moved to src/unit_tests/jl_parity.rs.
// JSON fixtures remain in tests/data/jl/ and are generated by
// scripts/jl/generate_testdata.jl.
