name = "ReductionProofs"
version = "0.1.0"
defaultTargets = ["reductionproofs"]

[[require]]
name = "mathlib"
scope = "leanprover-community"
version = "git#master"

[[lean_lib]]
name = "ReductionProofs"

[[lean_exe]]
name = "reductionproofs"
root = "Main"
